[package]
name = "asgn1"
version = "0.1.0"
edition = "2021"
author = "Taya Nicholas"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc", features = ["serde"] }